### ISSUE TITLE
About number in Train_Annotation.txt 

### ISSUE THREAD

**Issue by liujinhu217** [MKowal2/Real-World-Anomaly-Detection-PyTorch#2]
Vandalism/Vandalism048_ X264.mp4 7183 is  a line in Train_ Annotation.txt. I want to know What  7183 mean. 
Arson/Arson022_x264.mp4 8640 Arson 3500 4000 -1 -1 is  a line in Test_Annotation.txt.I want to know What do the numbers mean?( 8640 Arson 3500 4000 -1 -1)
thank you for help!

**Comment by MKowal2** [comment]
The numbers indicates the range of frames where anomalies occur. For anomaly1 and anomaly2 the format is: anomaly1_start anomaly1_end anomaly2_start anomaly2_end
3500 4000 -1 -1 means anomaly between frames 3500-4000.
-1 -1 means no second anomaly in the video.

Notice that all normal video are annotated with -1 -1 -1 -1, thus no anomalies in these videos.
All anomaly videos have at least one pair (and at most two pairs) of numbers, indicating the frames range.
